### ISSUE TITLE
Improvement on position of current word being typed

### ISSUE THREAD

**Issue by KAGEYAM4** [ColemakCamp/colemakcamp.github.io#1]
![image](https://github.com/ColemakCamp/colemakcamp.github.io/assets/75798544/25ba1d24-9837-4949-bfe5-ef9c404675db)

Comming from monkeytype, keybr where the only the cursor and line moves. Here the whole words moves suddenly which seems weird and takes time getting used to, also the fact that the word is off-center to the left.

First time using colemak training website. Is there any-reasoning behind it because i can see the same thing here - https://gnusenpai.net/colemakclub/

**Comment by NaeemBolchhi** [comment]
That's just how the single line mode works. You can use the paragraph mode from the menu to avoid that word movement. I'd like to make it like monkeytype, but it's not an easy thing to code, and I don't think I'm skilled enough for that yet.

Try the paragraph mode for now. Hopefully that'll be more to your liking.

**Comment by KAGEYAM4** [comment]
Didn't knew there was this option.

I am sure if you want this issue to be closed or kept open. I will leave it up to you.
