### ISSUE TITLE
Change Color of the text underline

### ISSUE THREAD

**Issue by AlvesJorge** [ColemakCamp/colemakcamp.github.io#4]
Please see the issue I posted on the colemak club 
https://github.com/gnusenpai/colemakclub/issues/43

If you agree I can create the PR for the change

**Comment by NaeemBolchhi** [comment]
![image](https://github.com/ColemakCamp/colemakcamp.github.io/assets/42773187/9255cd48-a64b-4e09-a02c-84d4d89437c5)

I don't think Colemak Club has that issue given that it uses a different font and there's enough space between the letter and the underline mark. Closing as not planned.
